### ISSUE TITLE
what about babel@^7 support

### ISSUE THREAD

**Issue by a-x-** [danielbayley/jest-preset-coffeescript#1]
hey, 
looks like jest-preset-coffeescript does not work with 7th version of babel 

config:
```
  "jest": {
    "preset": "jest-preset-coffeescript",
    "testRegex": "test\\.(coffee|litcoffee|coffee.md)$"
  },
```

<details><summary>error:</summary>

```
 FAIL  utils/iterator.test.coffee
  ● Test suite failed to run

    [BABEL] unknown: Plugin/Preset files are not allowed to export objects, only functions.

      at createDescriptor (node_modules/@babel/core/lib/config/option-manager.js:466:11)
      at node_modules/@babel/core/lib/config/option-manager.js:173:12
          at Array.map (<anonymous>:null:null)
      at node_modules/@babel/core/lib/config/option-manager.js:172:48
      at cachedFunction (node_modules/@babel/core/lib/config/caching.js:40:17)
      at node_modules/@babel/core/lib/config/option-manager.js:90:14
          at Array.map (<anonymous>:null:null)
      at OptionManager.mergeConfigChain (node_modules/@babel/core/lib/config/option-manager.js:89:43)
      at OptionManager.init (node_modules/@babel/core/lib/config/option-manager.js:114:12)
      at manageOptions (node_modules/@babel/core/lib/config/option-manager.js:33:30)
      at loadConfig (node_modules/@babel/core/lib/config/index.js:15:37)
      at transformSync (node_modules/@babel/core/lib/transform-sync.js:13:36)
      at Object.transform (node_modules/@babel/core/lib/transform.js:20:65)
      at CoffeeScript.transpile (node_modules/coffeescript/lib/coffeescript/index.js:26:18)
      at Object.<anonymous> (node_modules/coffeescript/lib/coffeescript/coffeescript.js:187:26)
      at Object.<anonymous> (node_modules/coffeescript/lib/coffeescript/coffeescript.js:54:19)
      at CoffeeScript.compile (node_modules/coffeescript/lib/coffeescript/index.js:41:29)
      at Object.exports.process (node_modules/jest-preset-coffeescript/index.js:17:36)
          at Generator.next (<anonymous>:null:null)
          at new Promise (<anonymous>:null:null)
          at Generator.next (<anonymous>:null:null)
          at <anonymous>:null:null
      at process._tickCallback (internal/process/next_tick.js:188:7)
```

</details>

**Comment by a-x-** [comment]
<details><summary>babel dependencies (7.0.0-beta.34):</summary>

```
    "@babel/cli": "^7.0.0-beta.34",
    "@babel/core": "^7.0.0-beta.34",
    "@babel/plugin-proposal-optional-chaining": "^7.0.0-beta.34",
    "@babel/plugin-syntax-dynamic-import": "^7.0.0-beta.34",
    "@babel/plugin-transform-destructuring": "^7.0.0-beta.34",
    "@babel/plugin-transform-runtime": "^7.0.0-beta.34",
    "@babel/plugin-transform-shorthand-properties": "^7.0.0-beta.34",
    "@babel/preset-env": "^7.0.0-beta.34",
    "@babel/preset-react": "^7.0.0-beta.34",
    "@babel/preset-stage-1": "^7.0.0-beta.34",
```

</details>

**Comment by a-x-** [comment]
My working coffeescript2+jest+react+babel7 solution with custom preprocessor

<details><summary>package.json (extract):</summary>

```json
{
  "devDependencies": {
    "@babel/cli": "^7.0.0-beta.34",
    "@babel/core": "^7.0.0-beta.34",
    "@babel/plugin-proposal-optional-chaining": "^7.0.0-beta.34",
    "@babel/plugin-syntax-dynamic-import": "^7.0.0-beta.34",
    "@babel/plugin-transform-destructuring": "^7.0.0-beta.34",
    "@babel/plugin-transform-shorthand-properties": "^7.0.0-beta.34",
    "@babel/preset-env": "^7.0.0-beta.34",
    "@babel/preset-es2015": "^7.0.0-beta.34",
    "@babel/preset-react": "^7.0.0-beta.34",
    "@babel/preset-stage-1": "^7.0.0-beta.34",
    "babel-core": "^7.0.0-bridge.0",
    "babel-jest": "^21.2.0",
    "babel-preset-jest": "^22.1.0",
    "body-parser": "^1.18.2",
    "coffeescript": "^2.1.0",
    "jest": "^21.2.1",
    "jest-coffee-preprocessor": "^1.0.0",
    "jest-preset-coffeescript": "^1.0.0",
  },
  "jest": {
    "testRegex": "\\.test\\.coffee$",
    "transform": {
      "\\.coffee$": "<rootDir>/utils/jest-coffee-preprocessor/index.js",
      "\\.jsx?$": "babel-jest"
    },
    "moduleFileExtensions": [
      "js",
      "jsx",
      "coffee"
    ]
  },
}
```

</details>

<details><summary>utils/jest-coffee-preprocessor/index.js</summary>

```js
const coffee = require('coffeescript');
const babel = require('@babel/core');
const jestPreset = require('babel-preset-jest');
const envPreset = require('@babel/preset-es2015');

exports.process = (source, file) => {
  if (!coffee.helpers.isCoffee(file)) {
    return source;
  }
  const es6Src = coffee.compile(source, {
    bare: true,
    inlineMap: true,
    transpile: undefined, // don't use coffeescript babel transpilation
  });
  return babel.transform(es6Src, {
    envName: 'test',
    sourceMaps: 'inline',
    presets: [jestPreset, [envPreset, {
      modules: 'commonjs',
      targets: { node: true },
    }]],
  }).code;
};
```

</details>

**Comment by danielbayley** [comment]
Thanks @a-x-, I'll look into this as soon as I can…

**Comment by MicMonen** [comment]
Any updates on this?

**Comment by laurentpayot** [comment]
[CoffeeScript now indifferently uses Babel 6 or 7](https://coffeescript.org/#changelog), so jest-preset-coffeescript also works but it forces install of Babel 6. It would be nice to upgrade to Babel 7 indeed.

**Comment by a-x-** [comment]
jfyi, we started to move from coffee2 to es6+jsx+optional-chaining ;)

Thanks to [decaffeinate](https://github.com/decaffeinate/decaffeinate) (I use [my forked version with re-enabled optional-chaining support](https://github.com/a-x-/decaffeinate))

**Comment by a-x-** [comment]
And, may be you'll be interested in plugin for eslint that I [initially created](https://github.com/a-x-/eslint-plugin-coffeescript) based on [solution posted here](https://github.com/danielbayley/jest-preset-coffeescript/issues/1#issuecomment-359163636)

Community improved it even more:
https://www.npmjs.com/package/@fellow/eslint-plugin-coffee

We lived much better with eslint+coffee last year

**Comment by laurentpayot** [comment]
I see JavaScript and even more TypeScript as a good choice for corporate people as it enforces standards and communication between teams.
As an independent developer for me CoffeeScript (with [Floweret](https://github.com/laurentpayot/floweret#coffeescript)) is a better choice because it improves my productivity. :wink:

**Comment by danielbayley** [comment]
There was a CoffeeScript [update] ([`2.3.2`]) to support Babel 7, so I just updated dependencies and fixed a small issue that seemed to throw up… but it should be fully supported now.

@a-x- @laurentpayot @MicMonen CI passed obviously; but please test and confirm that it works. Thanks!

[update]: https://coffeescript.org/#changelog
[`2.3.2`]: https://github.com/jashkenas/coffeescript/compare/2.3.1...2.3.2

**Comment by laurentpayot** [comment]
@danielbayley  Awesome. Will test on Monday.

**Comment by laurentpayot** [comment]
@danielbayley [Tests passed](https://travis-ci.org/laurentpayot/floweret/jobs/520308272). Thanks for the update :+1:
