### ISSUE TITLE
SyntaxError: Unexpected token z in JSON at position 0

### ISSUE THREAD

**Issue by MahdiFakhrabadi** [danielbayley/jest-preset-coffeescript#51]
I've followed your installation instruments carefully, but I'm getting this error while running "jest":

 FAIL  test/auth.test.coffee
  ● Test suite failed to run

    SyntaxError: Unexpected token z in JSON at position 0
        at JSON.parse (<anonymous>)

      at Object.parseSourceMapInput (node_modules/source-map/lib/util.js:433:15)
      at new SourceMapConsumer (node_modules/source-map/lib/source-map-consumer.js:17:22)
      at mapSourcePosition (node_modules/source-map-support/source-map-support.js:200:14)
      at wrapCallSite (node_modules/source-map-support/source-map-support.js:377:20)
      at Function.prepareStackTrace (node_modules/source-map-support/source-map-support.js:426:39)
      at enhanceUnexpectedTokenMessage (node_modules/@jest/transform/build/enhanceUnexpectedTokenMessage.js:76:7)
      at handlePotentialSyntaxError (node_modules/@jest/transform/build/enhanceUnexpectedTokenMessage.js:43:11)
      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:586:56)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:607:25)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        3.18 s
Ran all test suites.

Content of "auth.test.coffee":
```
describe "Strings test", =>
  it "Testing two strings are the same", =>
    expect("A spade").toBe "A spade"
```

Would appreciate any help.

**Comment by MahdiFakhrabadi** [comment]
Tried https://github.com/nicolindemann/jest-coffee-preprocessor and works well. Therefore closing this issue.
